/**
 * gemini.ts
 * 
 * Google Gemini 2.0 Flash AI integration for trivia generation
 * Reference: blueprint:javascript_gemini_ai_integrations
 * Handles structured JSON output with retry logic
 */

import { GoogleGenAI, Type } from "@google/genai";

// Initialize Gemini AI client using Replit AI Integrations
const ai = new GoogleGenAI({
  apiKey: process.env.AI_INTEGRATIONS_GEMINI_API_KEY!,
  httpOptions: {
    apiVersion: "",
    baseUrl: process.env.AI_INTEGRATIONS_GEMINI_BASE_URL!,
  },
});

interface TriviaQuestion {
  question: string;
  options: string[];
  correctAnswer: string;
}

/**
 * Generate trivia questions for a movie using Gemini AI with structured JSON output
 * @param movieTitle - The title of the movie to generate trivia for
 * @returns Array of trivia questions with options and correct answers
 */
export async function generateMovieTrivia(movieTitle: string): Promise<TriviaQuestion[]> {
  try {
    const systemPrompt = `You are the Krittics Deep Dive Trivia Generator. Your task is to create 5 unique, engaging, spoiler-free trivia questions focused on plot details, memorable quotes, characters, or behind-the-scenes facts for the movie: "${movieTitle}". 

Each question should:
- Be specific and interesting
- Have exactly 4 multiple-choice options
- Include only ONE correct answer
- Avoid revealing major plot twists or endings
- Be answerable by someone who has watched the movie
- Mix difficulty levels (some easy, some challenging)

The response must be a valid JSON array matching the provided schema.`;

    const userQuery = `Generate 5 Deep Dive Trivia questions for the movie "${movieTitle}".`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          role: "user",
          parts: [{ text: userQuery }],
        },
      ],
      systemInstruction: {
        parts: [{ text: systemPrompt }],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          description: "An array of trivia question objects",
          items: {
            type: Type.OBJECT,
            properties: {
              question: {
                type: Type.STRING,
                description: "The trivia question",
              },
              options: {
                type: Type.ARRAY,
                description: "Four multiple-choice options including the correct answer",
                items: { type: Type.STRING },
              },
              correctAnswer: {
                type: Type.STRING,
                description: "The text of the correct option (must match one of the options exactly)",
              },
            },
            required: ["question", "options", "correctAnswer"],
          },
        },
      },
    });

    const jsonText = response.text || "";
    if (!jsonText) {
      throw new Error("No trivia content was generated by the model");
    }

    const parsedTrivia = JSON.parse(jsonText) as TriviaQuestion[];

    // Validate that we got the expected number of questions
    if (!Array.isArray(parsedTrivia) || parsedTrivia.length === 0) {
      throw new Error("Invalid trivia format returned from AI");
    }

    // Validate each question has the required fields
    for (const question of parsedTrivia) {
      if (!question.question || !Array.isArray(question.options) || !question.correctAnswer) {
        throw new Error("Invalid question structure in AI response");
      }
      if (question.options.length !== 4) {
        throw new Error("Each question must have exactly 4 options");
      }
      if (!question.options.includes(question.correctAnswer)) {
        throw new Error("Correct answer must be one of the options");
      }
    }

    return parsedTrivia;
  } catch (error) {
    console.error("Gemini trivia generation error:", error);
    throw new Error(
      `Failed to generate trivia for "${movieTitle}": ${error instanceof Error ? error.message : "Unknown error"}`
    );
  }
}

/**
 * Generate trivia with retry logic and exponential backoff for reliability
 * @param movieTitle - The title of the movie
 * @param maxRetries - Maximum number of retry attempts (default: 3)
 * @returns Array of trivia questions
 */
export async function generateMovieTriviaWithRetry(
  movieTitle: string,
  maxRetries: number = 3
): Promise<TriviaQuestion[]> {
  let lastError: Error | null = null;

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      return await generateMovieTrivia(movieTitle);
    } catch (error) {
      lastError = error instanceof Error ? error : new Error("Unknown error");
      console.warn(`Trivia generation attempt ${attempt + 1} failed:`, lastError.message);

      // Don't retry on the last attempt
      if (attempt < maxRetries - 1) {
        const delay = Math.pow(2, attempt) * 1000; // Exponential backoff: 1s, 2s, 4s
        console.log(`Retrying in ${delay}ms...`);
        await new Promise((resolve) => setTimeout(resolve, delay));
      }
    }
  }

  throw lastError || new Error("Failed to generate trivia after multiple attempts");
}
