import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

export default function Article4() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto max-w-4xl px-4 py-12">
        <Link href="/insights">
          <button className="flex items-center gap-2 text-primary hover:underline mb-6" data-testid="link-back-insights">
            <ArrowLeft className="h-4 w-4" />
            Back to Krittics Insights
          </button>
        </Link>

        <article className="prose prose-invert max-w-none">
          <h1 className="font-display text-4xl font-bold text-foreground mb-2">
            Licensing 101 for AVOD Startups: Navigating Content Rights for Sustainable Growth
          </h1>
          <p className="text-muted-foreground mb-8"><em>Published: November 18, 2025</em></p>

          <p className="text-foreground mb-6">
            In the streaming wars, content is king, but licensing is the crown jewel. For new AVOD services, securing a compelling content library without the massive budgets of major studios is the primary challenge. The Krittics approach is one of strategic, low-cost acquisition, ensuring we focus our resources on platform innovation (like Krossfire) and user experience.
          </p>
          <p className="text-foreground mb-6">
            Content licensing is not just about having movies to show; it's about securing the legal right for a <strong>"public performance"</strong> and ensuring the platform is protected from expensive copyright infringement claims.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">I. The Strategic Importance of Low-Cost Content</h2>
          <p className="text-foreground mb-4">
            Traditional AVOD often relies on expensive deals with large production houses. This model leads to high fixed content costs and severely limits a startup's ability to innovate. Our strategy focuses on three pillars of legally sound, cost-effective content acquisition:
          </p>

          <h3 className="text-xl font-semibold text-foreground mt-6 mb-3">A. The Public Domain Advantage</h3>
          <p className="text-foreground mb-4">
            Works in the <strong>Public Domain (PD)</strong> are creative works where the copyright has expired, been forfeited, or was never established. These works are free for anyone to use, adapt, and distribute without seeking permission or paying royalties.
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground mb-4">
            <li><strong>Classic Content:</strong> PD films include cultural touchstones, especially those released before 1929, or films where the copyright was not properly renewed between 1930 and 1963. These titles, like <em>Night of the Living Dead</em>, <em>Nosferatu</em>, or <em>The General</em>, provide instant historical and artistic value to our library.</li>
            <li><strong>Cautionary Note:</strong> It is essential to confirm the status of <strong>underlying rights</strong> (such as the original music or book the film was based on) as they may still be protected, making thorough legal review necessary for every title.</li>
          </ul>

          <h3 className="text-xl font-semibold text-foreground mt-6 mb-3">B. Creative Commons (CC) and Open Source</h3>
          <p className="text-foreground mb-4">
            Many modern filmmakers, government agencies, and organizations release their work under <strong>Creative Commons (CC)</strong> licenses or similar open-source models.
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground mb-4">
            <li><strong>Free to Use:</strong> These licenses allow platforms like Krittics to legally rebroadcast content, often requiring only proper attribution to the original creator. This is a common method for acquiring high-quality short films, animation (like Sintel, which we use for demonstration), and documentary footage.</li>
            <li><strong>Community Building:</strong> Supporting CC filmmakers aligns with our mission of rewarding creators and viewers, fostering a community that values accessibility and shared intellectual property.</li>
          </ul>

          <h3 className="text-xl font-semibold text-foreground mt-6 mb-3">C. Partnering with Independent Filmmakers</h3>
          <p className="text-foreground mb-4">
            Building relationships with independent creators is key to securing fresh, unique content that can differentiate Krittics from larger, more homogeneous streaming services.
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground mb-4">
            <li><strong>Ad Revenue Sharing:</strong> Instead of large upfront fees, we can partner with independent filmmakers, offering them a clear percentage of the <strong>ad revenue</strong> generated by their content. This approach ensures content acquisition costs remain tied directly to platform performance and user engagement.</li>
            <li><strong>Niche Appeal:</strong> Independent and niche content (documentaries, specific genres) helps Krittics identify and attract dedicated viewers, who are the source of our most valuable, high-retention traffic.</li>
          </ul>

          <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">II. Avoiding the Pitfalls: The Cost of Non-Compliance</h2>
          <p className="text-foreground mb-4">
            For any AVOD platform, the legal requirement for a <strong>public performance license</strong> is absolute. Failing to secure the rights for every piece of content, even if it's shown for free, is a serious risk.
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground mb-4">
            <li><strong>High Penalties:</strong> Copyright infringement carries severe penalties, including statutory damages up to <strong>$150,000 for willful infringement</strong> per work. This risk alone makes securing low-cost, legally clear content a non-negotiable business mandate.</li>
            <li><strong>Professionalism:</strong> A commitment to transparent, legal licensing signals professionalism and trustworthiness to both users and essential partners like <strong>Google Ad Manager</strong> and <strong>AdSense</strong>.</li>
          </ul>

          <p className="text-foreground mt-6">
            By focusing on content with explicitly clear rights (PD, CC) and establishing equitable revenue-sharing partnerships, Krittics builds a library that is not only compelling but also <strong>financially and legally sustainable</strong>, ensuring we can dedicate maximum resources to innovation and rewarding our users.
          </p>
        </article>
      </div>
    </div>
  );
}
