platform :ios do
  desc "Force manual signing for Appflow"
  # This lane name MUST match what Appflow expects
  lane :build_capacitor do
    # Call our real signing lane
    force_signing
  end

  private_lane :force_signing do
    update_project_team(
      path: "ios/App/App.xcodeproj",
      teamid: "9SA2W557K5"
    )

    update_project_provisioning(
      xcodeproj: "ios/App/App.xcodeproj",
      profile: ENV["SIGH_PROFILE_PATH"],
      target_filter: "App",
      build_configuration: "Release"
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      team_id: "9SA2W557K5",
      code_sign_identity: "Apple Distribution: Staton Blakely (9SA2W557K5)",
      profile_name: "Krittics App Store Profile"
    )
  end
end
